
server:
  port: 8080

# mybatis 配置
mybatis:
  type-aliases-package: com.dream.entity
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

## -------------------------------------------------

## SqlServer 配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pub?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root